### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by skariel**

### CODE REVIEW

**Comment by skariel** [comment]
@theindiepocalypse merge 123

**Comment by theindiepocalypse** [comment]
@skariel: Cannot merge right now. Maybe our DB is not yet in sync with Github. Please try again later...

**Comment by skariel** [comment]
@theindiepocalypse merge 123

**Comment by theindiepocalypse** [comment]
@skariel: merged!
The new ownership structure:



Owner | Percent
-------|---------
*total* | 100.0

**Pull request merged**
