### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by skariel**
klj lkj lkj klj lk j

 kj kj jl kj j 
@theindiepocalypse hi

### CODE REVIEW

**Comment by theindiepocalypse** [comment]
@skariel: hi!

**Comment by skariel** [comment]
@theindiepocalypse merge

**Comment by skariel** [comment]
@theindiepocalypse merge

**Comment by skariel** [comment]
@theindiepocalypse hi

**Comment by theindiepocalypse** [comment]
@skariel: hi!

**Comment by skariel** [comment]
@theindiepocalypse merge

**Comment by theindiepocalypse** [comment]
@skariel: merged!
The new ownership structure:



Owner | Percent
-------|---------
*total* | 100.0

**Pull request merged**
